version: '3.5'

services:
  merchant:
    image: merchant-rust
    container_name: merchant-rust
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - postgres

  postgres:
    image: postgres:15.1-alpine
    container_name: go-postgres
    environment:
      - POSTGRES_USER=vending
      - POSTGRES_PASSWORD=vending
      - POSTGRES_DB=vending
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8001:5432"